project_id = "cjosawtrjeyqavdsffuy"

[functions.import-musicdb]
verify_jwt = false

[functions.extract-jackets]
verify_jwt = false

[functions.update-eamuse-ids]
verify_jwt = false

[functions.fix-musicdb-rows]
verify_jwt = false

[functions.import-deleted-songs]
verify_jwt = false

[functions.import-sanbai-ratings]
verify_jwt = false
